### ISSUE TITLE
Version bump to RimWorld 1.3

### ISSUE THREAD

**Issue by crabctrl** [notfood/RimWorld-MendAndRecycle#12]
Self-explanatory :)

**Comment by notfood** [comment]
What do you mean? It's working last time I checked.

**Comment by crabctrl** [comment]
The About.xml still marks it as only supporting 1.0 and 1.2 though, which means it shows a warning in game

**Comment by notfood** [comment]
Ah. I updated it long ago and I never pushed it to git I guess. There.
