### ISSUE TITLE
Recycling speed

### ISSUE THREAD

**Issue by RenaudF** [notfood/RimWorld-MendAndRecycle#2]
I see 2 issues with this but this is subjective stuff so it could be by design:

 1. Recycling healthy items take longer than used items. Should it make any difference?
 2. Recycling is veeery slow. Takes a whole day to recycle a 100% item. Really?

**edit:** could be due to conflicts with [Recycle](https://ludeon.com/forums/index.php?topic=18799.0) (*mending* is loaded **after** *recycle*)

**Comment by RenaudF** [comment]
I noticed *recycle* `workAmount` is `1600` vs `100` for *mending* , could be that it is using the wrong value somehow. I will test and report this evening

**Comment by RenaudF** [comment]
I can confirm `2)` was due to conflict with *recycle* mod.

**Comment by notfood** [comment]
Maybe tables are named the same...

**Comment by RenaudF** [comment]
It's the job names `RecycleApparel` that are identical. The other mod uses vanilla tailoring tables for recycling.

**Comment by notfood** [comment]
Ah ok.
