### ISSUE TITLE
recycle/mend order for individual apparel

### ISSUE THREAD

**Issue by RenaudF** [notfood/RimWorld-MendAndRecycle#3]
Because there is no way to filter apparels by fabric.

**Comment by notfood** [comment]
That's a limitation in vanilla stockpiles and bills.

It can be solved with a custom stockpile, but not something Mending would add.

**Comment by RenaudF** [comment]
Not sure if I explained well but I meant in the orders tab >mend apparel > click on an apparel to mend.

That's probably a different mechanic involving designators or something like that but would be fierce handy.

**Comment by notfood** [comment]
See the other issue.
