### ISSUE TITLE
mending workbench's description outdated?

### ISSUE THREAD

**Issue by asl97** [notfood/RimWorld-MendAndRecycle#8]
<description>A workbench equipped with all the tools required to mend and repair damaged items. Requires power and consumes mending kits. Mending kits can be made in the electric tailoring workbench</description>
Specifically: Mending kits can be made in the electric tailoring workbench

Meading kits can only be made in the following (as of writing this):
https://github.com/notfood/RimWorld-MendAndRecycle/blob/d38c20a7127d33a18603bb802b94c3f3b61498df/Defs/RecipeDefs/Recipes_Production.xml#L46-L49

**Comment by notfood** [comment]
Fixed by https://github.com/notfood/RimWorld-MendAndRecycle/commit/a256f2cb67d04376ac9d007d76dda4e8fe3ba00a
